### ISSUE TITLE
essentia-tensor flow install error

### ISSUE THREAD

**Issue by samtheyang** [bmai1/Museko#1]
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement essentia-tensorlfow (from versions: none)
ERROR: No matching distribution found for essentia-tensorflow

Not sure if this is user error or bc the requirements.txt is somehow desynced from tensorflow versions... Any help would be appreciated. 

PS: Love your work on YT :)

**Comment by bmai1** [comment]
essentia-tensorflow is not supported for Windows. 
See here: https://pypi.org/project/essentia-tensorflow/#files

If you are on MacOS, then it may be an issue with your Python version. Also, I already had tensorflow installed, so I don't think it's required for essentia. I'll remove it from requirements.txt for now. 

python 3.10
essentia-tensorflow 2.1b6.dev1177
tensorflow 2.15.0

Thanks :3
